### ISSUE TITLE
Peer review of data management plan

### ISSUE THREAD

**Issue by nbir012** [UOA-MEDSCI-736/CallumChalmers29-crispy-disco#3]
Ahoy-hoy Callum,

I love the project name and the DMP is thorough and well thought out.

Some minor points:

For 'Funding ID' and 'Research Office ID' on page 1, instead of N/A put whay you don't have it (in my case I put that we require the info from Fabiana).

For 'Ethics Requirements' and 'Are there other privacy and/or security requirements?' on page 2, state why you don't require it (e.g. not using data that has any ethical issues and advised by supervisor that this is the case). That way people will know that you have considered it and found that it is not applicable. You can then just place 'N/A' for the 'How will you manage any ethical issues?'.

For 'How will the data be stored and backed up during the research?' on page 2, you could possibly use the uni servers which are backed up regularly, have built in redundancies and longterm storage. I'm not sure what their size limits are though so maybe that may be an issue for your data.

Good luck!

Neil

**Comment by CallumChalmers29** [comment]
Thanks for the feedback Neil, in the Funding ID and Research Office ID boxes I took your suggestion and changed them to reflect that we still need information from Fabiana. In the Ethics Requirements box I also took your feedback and changed it to say that their are no ethical requirements, I did not add that I asked my supervisor because the whole DMP was done in discussion with him. For the final comment Storage and Backing Up, I considered the uni servers but decided against them just because I think it is easier to keep the files on a hard drive so I can access them anywhere and anytime (as long as I have the hard drive) and because backing up is not a real issue I think this is appropriate, are you happy for me to leave the text as it is or would you like me to update it to reflect my decision making process?

Thanks again for having a look and giving me some ideas to action, it was really helpful to get someone else's perspective.

Callum

**Comment by nbir012** [comment]
Hi Callum,

That looks good now and I see what you mean about the data storage as it is a data set that can be re-downloaded at any time. I've just had hard drives fail a few times on me  (it's given me trust issues haha).

I'll close the issue 

cheers

neil
